apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goserver-hpa
spec:
  # hpa apontado para onde?
  # neste nosso caso vamos apontar para o deploymenbt
  scaleTargetRef:
    apiVersion: apps/v1
    name: goserver # name de quem será escalado
    kind: Deployment # quem será escalado
  minReplicas: 1 # qual o numero minimo de replicas que o hpa vai utilizar
                 # em prod, no minimo duas
  maxReplicas: 30 # quando der 5 replicas, não escala mais
  targetCPUUtilizationPercentage: 15 # quando chegar em 30% vai começar o processo de escala
                                     # grealmente o número será maior, mas aqui estamos aplicando somente para fins didaticos
                                    