apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql  
spec:
  replicas: 3
  serviceName: mysql-h #headless - identico ao nome do servico mysql-service-h.yaml
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec: # do pod
      containers:
        - name: mysql
          image: mysql/mysql-server:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume

  volumeClaimTemplates: # criar template de volume que será utilizado toda vez que houver escalamento
  - metadata:
      name: mysql-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
