apiVersion: v1
kind: ServiceAccount
metadata:
  name: server

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # o que a service account pode fazer
metadata:
  name: server-read
rules: # quais sao as regras
- apiGroups: [""] # determina quais sao recurso que vamos trqbalhar baseado na api que esse cara trabalha
                  # vazio pq os resources abaixo não possuem api
                  # vide kubectl api-resources
  resources: ["pods","services"] # pode trabalhar
  verbs: ["create", "get", "watch", "list"] # quais verbos - funcionalidades sobre os resources acima
- apiGroups: ["apps"] # determina quais sao recurso que vamos trqbalhar baseado na api que esse cara trabalha
  resources: ["deployments"] # pode trabalhar
  verbs: ["create","get", "watch", "list"] # quais verbos - funcionalidades sobre os resources acima

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: server-read-bind
subjects:
- kind: ServiceAccount # tipo de dado / recurso vamos atribuir aquela regra
  name: server
  namespace: dev
roleRef:
  kind: ClusterRole # atribuir pra aquele service account a role
  name: server-read
  apiGroup: rbac.authorization.k8s.io # qual api-group desse role