
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: circuit-breaker-servicex
spec:
  host: servicex-service.default.svc.cluster.local
  trafficPolicy:
    outlierDetection: 
      # consecutive5xxErrors: 20 # vai ativar após 20 erros 5xx consecutivos
      consecutiveGatewayErrors: 10 # no intervalo de 10 segundos
      interval: 20s
      baseEjectionTime: 30s # que irá ejetar por 30 segundos 
      maxEjectionPercent: 100 # 100% dos pod serão ejetados